### PR TITLE
Fix wistia downloading issue

### PR DESCRIPTION
**Pull request by sumeetweb**
Fixes issue #46 #47 #49 #50

This is a rough patch. It currently downloads videos in 1080p. I will add a quality selector switch later on.

### CODE REVIEW

**Comment by lbarria77** [comment]
Works for docker?

**Comment by sumeetweb** [comment]
Not tested. Should work. 😅

**Comment by lbarria77** [comment]
thanks, still download the files empty

**Comment by lbarria77** [comment]
image

**Comment by lbarria77** [comment]
i used an extension that give me this links 
`https://embed-cloudfront.wistia.com/deliveries/48022b3f098fdd12828a512b5e494e676e3632c2.m3u8`
`https://embed-cloudfront.wistia.com/deliveries/e7a1e33340ef926067da1a0f27302bd475643aeb.m3u8`
`https://fast.wistia.com/embed/medias/li2bdr47vp.m3u8`

im using docker, i have to install ffmpeg because in the readme says i have to run docker_compose up without ffmpeg

**Comment by sumeetweb** [comment]
The docker image now supports ffmpeg.

**Comment by sumeetweb** [comment]
@lbarria77 I see the html file is also empty.

**Comment by lbarria77** [comment]
Because i change one later  but it works

**Comment by sumeetweb** [comment]
Does it download the mp4 files?

**Comment by lbarria77** [comment]
Yes with live cat works, but video by video

**Comment by lbarria77** [comment]
The links that o send to you i changed the original to avoid problems.

**Comment by sumeetweb** [comment]
While downloading do you see the logs for https://embed-ssl.wistia.com/deliveries/ type links?

**Comment by lbarria77** [comment]
Let me verify, do you mean in the dev tools?

**Comment by lbarria77** [comment]
did you have telegram where i can sent you captures

**Comment by sumeetweb** [comment]
I fixed the lesson videos downloading.

**Comment by sumeetweb** [comment]
@lbarria77 You can reach me on telegram at @sumeetweb

**Comment by sumeetweb** [comment]
Quality selection for video downloading is added now. This fixes #22

**Comment by sumeetweb** [comment]
Downloaded video file name is now updated with content name.

**Comment by lbarria77** [comment]
thank you very much friend, it works perfectly now

**Pull request merged**
