### PR TITLE
Add download for additional html file when downloading a videofile

### PR DESCRIPTION
**Pull request by Methos76**
Also saves the HTML content from the page showing the video.
This is interesting for the activities in PacktPub courses, because the text is a transscript from the video, so code typed or presented in the video can be copied from this text.

### CODE REVIEW

**Comment by Ex-Communicad0** [comment]
can you add support for downloadable resources which inc. on the list

**Comment by Methos76** [comment]
> can you add support for downloadable resources which inc. on the list
> like this page https://i.imgur.com/C7df2RT.png

I would need a free course where such a list is provided, then it should be possible to implement that

**Comment by sumeetweb** [comment]
> can you add support for downloadable resources which inc. on the list
> 
> like this page https://i.imgur.com/C7df2RT.png

I need such a website with a free course where these items list is published. It's pending until I get a hold of such an account with those content types mainly Quiz, Assignment, PDF, Download and Survey type.

**Comment by sumeetweb** [comment]
> Also saves the HTML content from the page showing the video.
> This is interesting for the activities in PacktPub courses, because the text is a transscript from the video, so code typed or presented in the video can be copied from this text.

Yes, It already downloads the exercise's text as a html file along with the video file and stores in a folder. So no need for a pull, I guess.

**Comment by Methos76** [comment]
In my Case it did not do that.  When the video and the exercise description are on the same page, only the video was downloaded. That is the reason why I added the code that I provided with the pull request

**Pull request closed without merging**
